spring:
  main:
    banner-mode: off
  jpa:
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        default_schema: hibernate_basics
  datasource:
    url: "jdbc:postgresql://localhost:5432/mydatabase"
    username: "myuser" # pragma: allowlist secret
    password: "mypassword" # pragma: allowlist secret
    driver-class-name: org.postgresql.Driver
    hikari:
      minimum-idle: 2
      keepalive-time: 300000
      data-source-properties:
        ApplicationName: ${app.name}-${app.version}
      maximum-pool-size: 30
  liquibase:
    contexts: main
    enabled: true
    change-log: "classpath:/db/changelog/changelog-main.yml"
    liquibase-schema: public
    database-change-log-lock-table: liquibase_lock_conditions
    database-change-log-table: liquibase_changelog_conditions
  application:
    name: hibernateBasics
