# Standard test profile
spring:
  jpa:
    show-sql: true
    properties:
      hibernate.format_sql: false
    hibernate:
      ddl-auto: create
  liquibase:
    contexts: test
    enabled: true

logging:
  level:
    root: INFO
    org:
      springframework:
        test:
          context:
            cache: DEBUG

management:
  metrics:
    export:
      prometheus:
        enabled: true

authorization:
  entitlementBaseUrl: http://localhost


